// ================================================================================================================== //
// Auto generated file created at Thursday, 20-Jan-22 15:56:07 EST. Do not edit this file, edit generation code.
// ================================================================================================================== //

package interpreter

type SExpression interface {
	GetName() string
}

/*
The most elementary type of S-Expression is the atomic symbol.

Definition: An atomic symbol is a string of no more than thirty numerals and capital
letters; the first character must be a letter.

Examples:
	A
	APPLE
	PART2
	EXTRALONGSTRINGOFLETTERS
	A4B66XYZ2
*/
type Atom struct {
	name string
}

func (a Atom) GetName() string {
	return "Atom"
}

type List struct {
	sexps []SExpression
}

func (l List) GetName() string {
	return "List"
}

type LParen struct{}

func (a LParen) GetName() string { 
	return "LParen"
}

type RParen struct{}

func (a RParen) GetName() string { 
	return "RParen"
}

type Dot struct{}

func (a Dot) GetName() string { 
	return "Dot"
}

type LSquareBracket struct{}

func (a LSquareBracket) GetName() string { 
	return "LSquareBracket"
}

type RSquareBracket struct{}

func (a RSquareBracket) GetName() string { 
	return "RSquareBracket"
}

type Semicolon struct{}

func (a Semicolon) GetName() string { 
	return "Semicolon"
}
